name: Security

on:
  workflow_call:

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./shell/.shock/actions/envrc
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install govulncheck
        run: ./shell/shock workspace govulncheck
      - name: Run govulncheck
        run: govulncheck ./...
